package database

import (
	"go-manger/internal/domain/model"
	"go-manger/internal/domain/service"
)

func SeedRestaurants() {
	var count int64
	DB.Model(&model.Restaurant{}).Count(&count)

	if count == 0 {
		restaurants := []model.Restaurant{
			{
				Name:        "Le Charme Parisien",
				Description: "Découvrez la cuisine Française",
				Image:       "image-url-1",
				Email:       "restaurant1@example.com",
				Password:    "password1",
				MenuItems: []model.MenuItem{
					{
						Name:         "Soupe à l'oignon",
						Description:  "Une soupeavec des oignons caramélisés, du bouillon de bœuf, du vin blanc, garnie de croûtons et de fromage gruyère gratiné.",
						Available:    true,
						Type:         model.MenuItemStarter,
						Price:        8,
						RestaurantID: 1,
					},
					{
						Name:         "Salade Niçoise",
						Description:  "Thon, œufs durs, olives noires, tomates, haricots verts, pommes de terre et vinaigrette à l'ail.",
						Available:    true,
						Type:         model.MenuItemStarter,
						Price:        12,
						RestaurantID: 1,
					},
					{
						Name:         "Boeuf Bourguignon",
						Description:  "Ragoût de bœuf mijoté dans du vin rouge avec des champignons, des petits oignons, et des lardons, servi avec des pâtes fraîches.",
						Available:    true,
						Type:         model.MenuItemDish,
						Price:        18,
						RestaurantID: 1,
					},
					{
						Name:         "Ratatouille",
						Description:  "Un mélange de légumes méditerranéens cuits lentement, servi avec du riz basmati.",
						Available:    true,
						Type:         model.MenuItemDish,
						Price:        15,
						RestaurantID: 1,
					},
					{
						Name:         "Crème Brûlée",
						Description:  "Crème onctueuse à la vanille sous une couche caramélisée croquante.",
						Available:    true,
						Type:         model.MenuItemDessert,
						Price:        7,
						RestaurantID: 1,
					},
					{
						Name:         "Tarte Tatin",
						Description:  "Tarte aux pommes caramélisées, servie tiède avec une boule de glace vanille.",
						Available:    true,
						Type:         model.MenuItemDessert,
						Price:        6,
						RestaurantID: 1,
					},
					{
						Name:         "Vin rouge Côtes du Rhône",
						Description:  "Un vin équilibré avec des notes de fruits rouges et d'épices.",
						Available:    true,
						Type:         model.MenuItemDrink,
						Price:        5,
						RestaurantID: 1,
					},
					{
						Name:         "Eau minérale",
						Description:  "Bouteille de 500 ml.",
						Available:    true,
						Type:         model.MenuItemDrink,
						Price:        3,
						RestaurantID: 1,
					},
				},
			},
			{
				Name:        "La Dolce Vita",
				Description: "Découvrez la cuisine Italienne",
				Image:       "image-url-2",
				Email:       "restaurant2@example.com",
				Password:    "password2",
				MenuItems: []model.MenuItem{
					{
						Name:         "Bruschetta",
						Description:  "Pain grillé avec des tomates fraîches, de l'ail, du basilic et de l'huile d'olive extra vierge.",
						Available:    true,
						Type:         model.MenuItemStarter,
						Price:        6,
						RestaurantID: 2,
					},
					{
						Name:         "Carpaccio de bœuf",
						Description:  "Fines tranches de bœuf cru, arrosées d'huile d'olive et de citron, garnies de copeaux de parmesan.",
						Available:    true,
						Type:         model.MenuItemStarter,
						Price:        10,
						RestaurantID: 2,
					},
					{
						Name:         "Lasagne à la Bolognaise",
						Description:  "Couches de pâtes avec sauce bolognaise, béchamel, et fromage gratiné.",
						Available:    true,
						Type:         model.MenuItemDish,
						Price:        14,
						RestaurantID: 2,
					},
					{
						Name:         "Risotto aux champignons",
						Description:  "Risotto crémeux aux champignons Porcini et parmesan.",
						Available:    true,
						Type:         model.MenuItemDish,
						Price:        13,
						RestaurantID: 2,
					},
					{
						Name:         "Tiramisu",
						Description:  "Mascarpone, café fort, biscuits à la cuillère imbibés de café et saupoudrés de cacao.",
						Available:    true,
						Type:         model.MenuItemDessert,
						Price:        7,
						RestaurantID: 2,
					},
					{
						Name:         "Panna Cotta",
						Description:  "Crème cuite vanillée, nappée d'un coulis de fruits rouges.",
						Available:    true,
						Type:         model.MenuItemDessert,
						Price:        6,
						RestaurantID: 2,
					},
					{
						Name:         "Chianti",
						Description:  "Vin rouge toscan, fruité et bien structuré.",
						Available:    true,
						Type:         model.MenuItemDrink,
						Price:        5,
						RestaurantID: 2,
					},
					{
						Name:         "Limoncello",
						Description:  "Liqueur de citron italienne.",
						Available:    true,
						Type:         model.MenuItemDrink,
						Price:        4,
						RestaurantID: 2,
					},
				},
			},
			{
				Name:        "Le Dragon Impérial",
				Description: "Découvrez la cuisine Asiatique",
				Image:       "image-url-3",
				Email:       "restaurant3@example.com",
				Password:    "password3",
				MenuItems: []model.MenuItem{
					{
						Name:         "Rouleaux de printemps",
						Description:  "Rouleaux frais avec crevettes, vermicelles, laitue, menthe et coriandre, servis avec une sauce hoisin.",
						Available:    true,
						Type:         model.MenuItemStarter,
						Price:        5,
						RestaurantID: 3,
					},
					{
						Name:         "Soupe Miso",
						Description:  "Bouillon de miso avec tofu, algues wakame et échalotes.",
						Available:    true,
						Type:         model.MenuItemStarter,
						Price:        4,
						RestaurantID: 3,
					},
					{
						Name:         "Canard laqué à la Pékinoise",
						Description:  "Canard croustillant servi avec des crêpes, des concombres, des oignons verts et de la sauce hoisin.",
						Available:    true,
						Type:         model.MenuItemDish,
						Price:        20,
						RestaurantID: 3,
					},
					{
						Name:         "Curry vert thaï",
						Description:  "Poulet, aubergines, poivrons et basilic thaï dans une sauce au curry vert et lait de coco, servi avec du riz jasmin.",
						Available:    true,
						Type:         model.MenuItemDish,
						Price:        14,
						RestaurantID: 3,
					},
					{
						Name:         "Mochi glacé",
						Description:  "Boules de glace enveloppées dans une pâte de riz douce, assortiment de saveurs.",
						Available:    true,
						Type:         model.MenuItemDessert,
						Price:        5,
						RestaurantID: 3,
					},
					{
						Name:         "Mango Sticky Rice",
						Description:  "Riz gluant avec mangue fraîche et lait de coco.",
						Available:    true,
						Type:         model.MenuItemDessert,
						Price:        6,
						RestaurantID: 3,
					},
					{
						Name:         "Thé vert japonais",
						Description:  "Thé vert rafraîchissant et riche en antioxydants.",
						Available:    true,
						Type:         model.MenuItemDrink,
						Price:        3,
						RestaurantID: 3,
					},
					{
						Name:         "Bière asiatique",
						Description:  "Bière légère et rafraîchissante.",
						Available:    true,
						Type:         model.MenuItemDrink,
						Price:        4,
						RestaurantID: 3,
					},
				},
			},
			{
				Name:        "El Sol Azteca",
				Description: "Découvre la cuisine Mexicaine",
				Image:       "image-url-4",
				Email:       "restaurant4@example.com",
				Password:    "password4",
				MenuItems: []model.MenuItem{
					{
						Name:         "Guacamole maison",
						Description:  "Avocats mûrs écrasés, oignons, tomates, coriandre, jus de citron vert, servi avec des chips de maïs croustillantes.",
						Available:    true,
						Type:         model.MenuItemStarter,
						Price:        6,
						RestaurantID: 4,
					},
					{
						Name:         "Quesadillas de fromage",
						Description:  "Tortillas de maïs grillées, garnies de fromage fondu, accompagnées de salsa verde.",
						Available:    true,
						Type:         model.MenuItemStarter,
						Price:        8,
						RestaurantID: 4,
					},
					{
						Name:         "Tacos al Pastor",
						Description:  "Tacos garnis de porc mariné et grillé, ananas, oignons rouges, coriandre, servis avec des quartiers de lime.",
						Available:    true,
						Type:         model.MenuItemDish,
						Price:        12,
						RestaurantID: 4,
					},
					{
						Name:         "Enchiladas Suizas",
						Description:  "Tortillas de maïs roulées et garnies de poulet, nappées d'une sauce verte crémeuse et gratinées au fromage.",
						Available:    true,
						Type:         model.MenuItemDish,
						Price:        14,
						RestaurantID: 4,
					},
					{
						Name:         "Churros",
						Description:  "Churros croustillants saupoudrés de sucre et de cannelle, servis avec une sauce au chocolat chaud.",
						Available:    true,
						Type:         model.MenuItemDessert,
						Price:        5,
						RestaurantID: 4,
					},
					{
						Name:         "Flan",
						Description:  "Crème caramel traditionnelle, douce et onctueuse.",
						Available:    true,
						Type:         model.MenuItemDessert,
						Price:        6,
						RestaurantID: 4,
					},
					{
						Name:         "Margarita classique",
						Description:  "Tequila, triple sec, jus de citron vert, servi sur glace avec une bordure de sel.",
						Available:    true,
						Type:         model.MenuItemDrink,
						Price:        7,
						RestaurantID: 4,
					},
					{
						Name:         "Horchata",
						Description:  "Boisson traditionnelle à base de riz, lait, vanille, et cannelle.",
						Available:    true,
						Type:         model.MenuItemDrink,
						Price:        4,
						RestaurantID: 4,
					},
				},
			},
			{
				Name:        "Vert Gourmand",
				Description: "Découvez la cuisine vegan",
				Image:       "image-url-5",
				Email:       "restaurant5@example.com",
				Password:    "password5",
				MenuItems: []model.MenuItem{
					{
						Name:         "Ceviche de champignons",
						Description:  "Champignons marinés dans une vinaigrette citronnée avec avocat, maïs et coriandre.",
						Available:    true,
						Type:         model.MenuItemStarter,
						Price:        9,
						RestaurantID: 5,
					},
					{
						Name:         "Tartare de betterave",
						Description:  "Betteraves, pommes vertes, noix, et une vinaigrette à l'érable et au balsamique.",
						Available:    true,
						Type:         model.MenuItemStarter,
						Price:        8,
						RestaurantID: 5,
					},
					{
						Name:         "Steak de chou-fleur",
						Description:  "Steak de chou-fleur rôti, purée de pois chiches, légumes de saison sautés et sauce tahini.",
						Available:    true,
						Type:         model.MenuItemDish,
						Price:        13,
						RestaurantID: 5,
					},
					{
						Name:         "Lasagne végane",
						Description:  "Lasagne avec couches de légumes grillés, ricotta d'amande, sauce tomate maison et fromage végétal.",
						Available:    true,
						Type:         model.MenuItemDish,
						Price:        12,
						RestaurantID: 5,
					},
					{
						Name:         "Tarte au citron meringuée végane",
						Description:  "Tarte crémeuse au citron sur une base de biscuit, meringue à base de jus de pois chiche.",
						Available:    true,
						Type:         model.MenuItemDessert,
						Price:        7,
						RestaurantID: 5,
					},
					{
						Name:         "Brownie au chocolat et noix",
						Description:  "Brownie riche et moelleux avec des morceaux de noix, servi avec une crème anglaise végane.",
						Available:    true,
						Type:         model.MenuItemDessert,
						Price:        6,
						RestaurantID: 5,
					},
					{
						Name:         "Smoothie boost énergétique",
						Description:  "Baies, banane, épinards, graines de chia et lait d'amande.",
						Available:    true,
						Type:         model.MenuItemDrink,
						Price:        5,
						RestaurantID: 5,
					},
					{
						Name:         "Thé glacé maison",
						Description:  "Thé noir infusé avec des pêches fraîches et un soupçon de menthe.",
						Available:    true,
						Type:         model.MenuItemDrink,
						Price:        3,
						RestaurantID: 5,
					},
				},
			},
		}

		for _, restaurant := range restaurants {
			hashedPassword, _ := service.HashPassword(restaurant.Password)

			restaurant.Password = string(hashedPassword)
			DB.Create(&restaurant)
		}
	}
}
